name: Terraform Destroy

on:
  workflow_dispatch:
 
permissions:
  id-token: write
  contents: write
  pull-requests: write
 
jobs:
  terraform:
    runs-on: ubuntu-latest
 
    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
 
      # Step 2: Configure AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
 
      # Step 3: Setup Terraform 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
 
      # Step 5: Terraform Init
      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Destroy
        run: terraform destroy -auto-approve
