name: Terraform Infra Destroy

on:
  workflow_dispatch:

jobs:
  # Job : Destroy Infrastructure using Terraform
  destroy-infra:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Configure AWS Credentials
      - name: Configure AWS credentials for Terraform
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Step 3: Set AWS region
      - name: Set AWS region
        run: echo "AWS_REGION=ap-south-1" >> $GITHUB_ENV 

      # Step 4: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      # Step 5: Terraform Init
      - name: Terraform Init
        run: terraform init

      # Step 6: Terraform Plan (optional, to preview destroy)
      - name: Terraform Plan
        run: terraform plan -destroy -var-file=env/dev/dev.tfvars

      # Step 7: Terraform Destroy
      - name: Terraform Destroy
        run: terraform destroy -var-file=env/dev/dev.tfvars -auto-approve
