name: Infrastructure Setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      # Install dependencies
      - name: Install dependencies
        run: |
          terraform init
          terraform validate

      # Run Terraform plan
      - name: Terraform plan
        run: terraform plan -var-file=terraform/dev/terraform.tfvars

      # Apply the Terraform plan (Infrastructure creation)
      - name: Terraform apply
        run: terraform apply -auto-approve -var-file=terraform/dev/terraform.tfvars

      # Optional: Save the Terraform output to GitHub Secrets or logs (optional)
      - name: Terraform output
        run: terraform output
