name: Infrastructure Setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-setup:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      # Install Terraform dependencies (initialize terraform)
      - name: Initialize Terraform
        run: terraform init

      # Validate Terraform configuration
      - name: Terraform Validate
        run: terraform validate

      # Run Terraform plan (dry-run to show the changes Terraform will apply)
      - name: Terraform Plan
        run: terraform plan -var-file=terraform/dev/terraform.tfvars

      # Apply Terraform changes (apply the plan and provision infrastructure)
      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=terraform/dev/terraform.tfvars

      # Optional: Output Terraform status
      - name: Terraform Output
        run: terraform output

  notify:
    runs-on: ubuntu-latest
    needs: terraform-setup
    steps:
      - name: Notify success or failure
        run: |
          echo "Infrastructure setup completed successfully!"
