name: Infrastructure Setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file=terraform/dev/terraform.tfvars

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=terraform/dev/terraform.tfvars

      - name: Terraform Output
        run: terraform output
